# Generated by Django 3.2.8 on 2021-10-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=500)),
                ('is_crawled', models.BooleanField(default=False)),
            ],
        ),
    ]
